### ISSUE TITLE
Momentary Mode for 5C

### ISSUE THREAD

**Issue by dirtydancing** [containerfan/anduril2-diagrams#1]
In the Advanced UI diagram, it might be useful to rename 5C from presently `Momentary` to `Momentary Mode`. This would apply to 5C from Off / On, as well as to 5C from the strobe / mood modes (cf. screenshot).

![Momentary-Mode](https://github.com/containerfan/anduril2-diagrams/assets/7164227/ab0b134f-1dbe-4ad6-999c-39f04286e7dd)

`Momentary Mode` seems fitting, as 5C Momentary is a mode in its own right, with the specific instruction to "Disconnect power to exit".

In addition, the term `Momentary Mode` would also be in line with ToyKeeper's [text manual](https://github.com/ToyKeeper/anduril/blob/312f7442c31d72dd36f108de9542f81960526658/docs/anduril-manual.md?plain=1#L577).

**Comment by containerfan** [comment]
Thanks for catching this.  Updated in release 2023-12-03.02.
