### ISSUE TITLE
Ramp 1H Up: Add reversing

### ISSUE THREAD

**Issue by dirtydancing** [containerfan/anduril2-diagrams#11]
Simple UI and Advanced UI diagrams:

It might be useful to add `, with reversing` to the present Ramp `1H Up`. This would indicate this function, and it would also be in line with [ToyKeeper's text manual](https://github.com/ToyKeeper/anduril/blob/cc228bd519d95a24a4ca17f491885f5539b6630b/docs/anduril-manual.md?plain=1#L999).

This sketch shows an example of how this information might be added:

![with_reversing](https://github.com/containerfan/anduril2-diagrams/assets/7164227/65809bd5-6b92-43a9-b970-7177a4c847a7)

**Comment by containerfan** [comment]
Fixed in release 2023-12-03.10.  Thanks for the suggestion!
