### ISSUE TITLE
Consistent use of channel mode in Simple UI

### ISSUE THREAD

**Issue by dirtydancing** [containerfan/anduril2-diagrams#12]
Simple UI diagram:

In continuation of https://github.com/containerfan/anduril2-diagrams/issues/8, it might avoid confusion to consistently make use of `channel mode` in the Simple UI diagram as well. In this case, this refers to 3H from ON, cf. screenshot, which might read `(if this channel mode can)`.

![channel_mode](https://github.com/containerfan/anduril2-diagrams/assets/7164227/82f84f6e-d6e6-4c65-85cd-19f6ecf6a8ea)

**Comment by containerfan** [comment]
Closed in release 2024-04-20.01.
