### ISSUE TITLE
Single Channel version

### ISSUE THREAD

**Issue by EpochalEngineer** [containerfan/anduril2-diagrams#13]
Thoughts on having a version/branch for single channel, with and without RGB aux lights?

**Comment by containerfan** [comment]
Thanks for the suggestion. I'm trying to keep the diagram as simple as possible in terms of maintenance due to limited time (as evidenced by my slow response), so my intention is to provide a "complete" diagram that folks can easily modify by deleting what they don't need using Inkscape.
