### ISSUE TITLE
ToyKeeper's Anduril User Manual link

### ISSUE THREAD

**Issue by dirtydancing** [containerfan/anduril2-diagrams#2]
Simple UI diagram and Advanced UI diagram:

The link to `ToyKeeper's Andúril User Manual` in the `Andúril 2` text box in the upper right corner (cf. screenshot) might be changed to the short link that ToyKeeper is providing at the [former manual link](https://toykeeper.net/torches/fsm/anduril2/anduril-manual.txt):

`https://toykeeper.net/anduril/manual`

![Manual-link](https://github.com/containerfan/anduril2-diagrams/assets/7164227/413468ea-db36-455d-b43a-8cde994e8cd3)

**Comment by containerfan** [comment]
Not sure how I missed the missing "s" in "https", but thank you for also providing ToyKeeper's  short URL for the text manual.  Updated in release 2023-12-03.02.
