### ISSUE TITLE
Consistent use of strobe / mood mode(s)

### ISSUE THREAD

**Issue by dirtydancing** [containerfan/anduril2-diagrams#4]
Advanced UI diagram:

For consistency, it might be helpful to use `strobe / mood mode(s)` every time, instead of sometimes only `strobe mode`.

This would apply to the `Actions` in the `Strobe / Mood Modes` group (cf. screenshot)

![strobe_mood_1](https://github.com/containerfan/anduril2-diagrams/assets/7164227/e3cfb591-99ea-40fc-99bf-efd0b4156f4d)

as well as to the `Tactical Slot Config` (cf. screenshot).

![strobe_mood_2](https://github.com/containerfan/anduril2-diagrams/assets/7164227/edc0a412-eecd-49cd-89b2-ac2b878c1155)

**Comment by containerfan** [comment]
Fixed in release 2023-12-03.04
