### ISSUE TITLE
Consistent use of current

### ISSUE THREAD

**Issue by dirtydancing** [containerfan/anduril2-diagrams#5]
Advanced UI diagram:

In addition to https://github.com/containerfan/anduril2-diagrams/issues/4, for the `Strobe / Mood Modes`, `Actions`, `5C`, it might be helpful to use `current` instead of presently `selected` (cf. screenshot).

![strobe_mood_current_1](https://github.com/containerfan/anduril2-diagrams/assets/7164227/9d8bb9f6-76f7-4d9a-9ce1-5ec44b8dde4b)

This way, the line for `5C` would be shorter, and furthermore, it would be consistent with the use of `current` elsewhere in the diagram (cf. screenshot).

![strobe_mood_current_2](https://github.com/containerfan/anduril2-diagrams/assets/7164227/0accf77b-3268-44c0-ba16-5e26a009d784)

**Comment by containerfan** [comment]
Fixed in release 2023-12-03.04.
