### ISSUE TITLE
Too much space in Misc Config text box

### ISSUE THREAD

**Issue by dirtydancing** [containerfan/anduril2-diagrams#6]
Advanced UI diagram:

At the bottom of the `Misc Config` text box, there is unusually much space, when compared to the other text boxes (cf. screenshot).

![text_box_space](https://github.com/containerfan/anduril2-diagrams/assets/7164227/1fd8d9c6-e390-41ce-aa61-1f174a4852da)

**Comment by containerfan** [comment]
Fixed in release 2023-12-03.04
