### ISSUE TITLE
No 3C for next channel mode in Tactical Mode

### ISSUE THREAD

**Issue by dirtydancing** [containerfan/anduril2-diagrams#7]
Advanced UI diagram:

ToyKeeper has clarified that in Tactical Mode, 3C should not be changing the channel mode, cf. https://github.com/ToyKeeper/anduril/issues/40#issuecomment-1925037027. Given this, it might be a good idea to remove the 3C from Tactical Mode text box (cf. screenshot).

(Presently, in Tactical Mode, 3C for next channel mode only works in certain settings, and in others it does not. E.g., it does *not* work when Manual Memory is activated, or when a strobe / mood mode other than the default Police Strobe is configured.)

![Tactical_Mode_3C](https://github.com/containerfan/anduril2-diagrams/assets/7164227/23e777b0-34f0-4143-82e6-c5b8a6987017)

**Comment by containerfan** [comment]
Fixed in diagram release 2023-12-03.06
