### ISSUE TITLE
Consistent use of channel mode in Channel Mode Config

### ISSUE THREAD

**Issue by dirtydancing** [containerfan/anduril2-diagrams#8]
Advanced UI diagram:

It might be helpful to consistently make use of `channel mode` in the `Channel Mode Config` text box, in order to differentiate between `channel mode` and `channel` (cf. screenshot); this would also be consistent with the use of `channel mode` elsewhere in the diagram.

![Channel_Mode_Config](https://github.com/containerfan/anduril2-diagrams/assets/7164227/b281474b-f296-4d5d-98ef-81ecef6ff828)

**Comment by containerfan** [comment]
Fixed in diagram release 2023-12-03.06
